<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'Capital' => '',
    'Cities' => 'Cidades',
    'City' => 'Cidade',
    'Code' => 'Código',
    'Code2' => 'Código2',
    'Continent' => 'Continente',
    'Countries' => '',
    'Country' => 'País',
    'Country Code' => 'Código do país',
    'Create' => 'Cadastrar',
    'Create City' => '',
    'Create Country' => '',
    'Create {modulo}' => 'Cadastrar {modulo}',
    'Delete' => '',
    'District' => 'Distrito',
    'Gnp' => 'GNP',
    'Gnpold' => '',
    'Government Form' => 'Forma do governo',
    'Head Of State' => 'Chefe de Estado',
    'ID' => '',
    'Indep Year' => 'Ano Indep',
    'Is Official' => 'É oficial',
    'Language' => 'Língua',
    'Life Expectancy' => 'Expectativa de vida',
    'Local Name' => 'Nome local',
    'Name' => 'Nome',
    'Percentage' => 'Percentagem',
    'Population' => 'População',
    'Region' => 'Região',
    'Reset' => '',
    'Search' => '',
    'Surface Area' => 'Área de superfície',
    'Update' => 'Alterar',
    'Update {modelClass}: ' => '',
    'Africa' => 'África',
    'Asia' => 'Ásia',
    'Antarctica' =>'Antartica',
    'Europe' => 'Europa',
    'North America'=>'America do Norte',
    'Oceania'=>'Oceania',
   'South America'=>'America do sul',
   'Countries of ' =>'Paises da ',
   'RememberMe' =>'Lembrar-me',
   'Username' =>'Usuário',

];
